mesh:
  shelves:
    pose: [0.85, 0, 0.4, 1, 0, 0, 0.0]
    file_path: "scene/shelves/shelves.obj"
  bin1:
    pose: [0, -0.6, 0, 1, 0, 0, 0.0]
    file_path: "scene/bin/bin.obj"
  bin2:
    pose: [0, 0.6, 0, 1, 0, 0, 0.0]
    file_path: "scene/bin/bin.obj"
  table:
    pose: [0.4, 0.0, 0.0, 1, 0, 0, 0.0]
    file_path: "scene/table/table_wide.obj"
  Bob:
    pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    file_path: "scene/Bob.obj"
  Face1:
    pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    file_path: "scene/Face1.obj"
  Face2:
    pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    file_path: "scene/Face2.obj"
  Face3:
    pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    file_path: "scene/Face3.obj"
  Cow:
    pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    file_path: "scene/Cow.obj"
  # City:
  #   pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
  #   file_path: "scene/City.obj"
  # Bridge:
  #   pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
  #   file_path: "scene/Bridge.obj"
  Fish:
    pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    file_path: "scene/Fish.obj"
  Sheep:
    pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    file_path: "scene/Sheep.obj"
  # Rose:
  #   pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
  #   file_path: "scene/Rose.obj"
  Board:
    pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    file_path: "scene/Snakeboard.obj"
  # Yeah:
  #   pose: [-0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
  #   file_path: "scene/Yeah.obj"